### ISSUE TITLE
Compilation issue on GCC 13.x

### ISSUE THREAD

**Issue by MtBud** [dungeons-of-moria/umoria#91]
Hi, tried to compile on Linux Mint 22, gcc version 13.3.0 and got the following error:

```
~/umoria-5.7.15/build$ make
[  1%] Building CXX object CMakeFiles/umoria.dir/src/config.cpp.o
[  3%] Building CXX object CMakeFiles/umoria.dir/src/helpers.cpp.o
...
[ 40%] Building CXX object CMakeFiles/umoria.dir/src/game_run.cpp.o
[ 42%] Building CXX object CMakeFiles/umoria.dir/src/game_save.cpp.o
/home/meffisto/umoria-5.7.15/src/game_save.cpp: In function ‘bool loadGame(bool&)’:
/home/meffisto/umoria-5.7.15/src/game_save.cpp:810:29: error: array subscript 66 is above array bounds of ‘Tile_t [66]
[198]’ [-Werror=array-bounds=]
  810 |                 if (tile >= &dg.floor[MAX_HEIGHT][0]) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/meffisto/umoria-5.7.15/src/headers.h:59,
                 from /home/meffisto/umoria-5.7.15/src/game_save.cpp:8:
/home/meffisto/umoria-5.7.15/src/dungeon.h:55:12: note: while referencing ‘Dungeon_t::floor’
   55 |     Tile_t floor[MAX_HEIGHT][MAX_WIDTH];
      |            ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/umoria.dir/build.make:370: CMakeFiles/umoria.dir/src/game_save.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/umoria.dir/all] Error 2
```

I changed the line throwing the error to the following and it compiled fine:
`if (tile > &dg.floor[MAX_HEIGHT-1][0]) {`

But i don't know if it messes up anything else, since i haven't even played the game yet and don't know how to test it :P

**Comment by raczek-piotr** [comment]
![Image](https://github.com/user-attachments/assets/23a0b291-4e7b-40e3-bbdd-1019c88e2be3)
ubuntu 22.04 (umoria 5.7.**14**)
błąd = error
but:
```
set(cxx_warnings "${cxx_warnings} -Wno-error=implicit-fallthrough")
set(cxx_warnings "${cxx_warnings} -Wno-error=missing-include-dirs")
```
doesn't work
g++ version = gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by raczek-piotr** [comment]
game_save.cpp (line 807) changed from
```
        tile = &dg.floor[0][0];
```
to:
```
        tile = &dg.floor[MAX_HEIGHT][MAX_WIDTH];
```

it works for me…
