### ISSUE TITLE
Compile on OpenBSD 7.3

### ISSUE THREAD

**Issue by lea2501** [dungeons-of-moria/umoria#69]
Hi! i wanted to compile in OpenBSD 7.3 (latest stable) and i get the following error:

```
lea@latitude5480 umoria $ cd build/
lea@latitude5480 build $ cmake ..
-- Build type set to 'Release'
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:27 (project):
  The CMAKE_CXX_COMPILER:

    g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/lea/src/umoria/build/CMakeFiles/CMakeOutput.log".
See also "/home/lea/src/umoria/build/CMakeFiles/CMakeError.log".

```

i added this packages already:
`doas pkg_add autoconf-2.71 gcc-11.2.0p6 gmake`

i also tried with this commands with same error:
`cmake .. -DCMAKE_MAKE_PROGRAM=gmake -DCMAKE_CXX_COMPILER=/usr/local/bin/eg++`

Thanks for mantaining this amazing game!

**Comment by lea2501** [comment]
I modified 'CMakeLists.txt' with this:
```
-set(CMAKE_CXX_COMPILER g++)
+set(CMAKE_CXX_COMPILER eg++)
```

And also file 'src/headers.h'
```
-#elif __APPLE__ ||  __linux__ || __NetBSD__ || __MORPHOS__
+#elif __APPLE__ ||  __linux__ || __NetBSD__ || __MORPHOS__ || __OpenBSD__
```

but now i'm getting:
```
/home/lea/src/umoria-color/src/game_save.cpp: In function 'bool loadGame(bool&)':
/home/lea/src/umoria-color/src/game_save.cpp:814:29: error: array subscript 66 is above array bounds of 'Tile_t [66][198]' [-Werror=array-bounds]
  814 |                 if (tile >= &dg.floor[MAX_HEIGHT][0]) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/lea/src/umoria-color/src/headers.h:60,
                 from /home/lea/src/umoria-color/src/game_save.cpp:8:
/home/lea/src/umoria-color/src/dungeon.h:56:12: note: while referencing 'Dungeon_t::floor'
   56 |     Tile_t floor[MAX_HEIGHT][MAX_WIDTH];
      |            ^~~~~
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/umoria.dir/build.make:384: CMakeFiles/umoria.dir/src/game_save.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/umoria.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

```
